pipeline {
  agent {
    node {
      label 'maven'
    }
  }
  options {
    timeout(time: 20, unit: 'MINUTES')
  }
  stages {
    stage('preamble') {
        steps {
            script {
                openshift.withCluster() {
                    openshift.withProject() {
                        echo "Using project: ${openshift.project()}"
                    }
                }
            }
            sh 'mkdir -p testresults; echo "test results" > testresults/test.txt'
        }
    }
  }

  post {
    always {
      archiveArtifacts artifacts: 'testresults/test.txt', fingerprint: true
    }
  }
}
