apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: openshift-load-tester
message: |-
  A complete Load Testing mechanism using Gatling
metadata:
  annotations:
    description: |-
      Launches a number of configured Gatling load test pods to exercise a target URL
    openshift.io/display-name: Pipeline Build Example
    tags: instant-app,jenkins
  name: openshift-load-tester
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: gatling-load-test-job
  spec:
    parallelism: 3
    completions: 3
    template:
      metadata:
        name: gatling-load-test-job
      spec:
        containers:
        - name: gatling-load-tester
          image: ${IMAGE}
        restartPolicy: Never
parameters:
- description: The docker image of the Gatling load tester
  displayName: Image
  name: IMAGE
  required: true
