apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: openshift-report-collater-job
  app: load-tester
message: |-
  collates reports from multiple gatling runs into a single report
metadata:
  annotations:
    description: |-
      collates reports from multiple gatling runs into a single report
    openshift.io/display-name: Gatling Report Collater
    tags: instant-app,jenkins
  name: openshift-report-collater-job
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: gatling-report-collater-job
  spec:
    parallelism: 1
    completions: 1
    template:
      metadata:
        name: gatling-report-collater-job
      spec:
        containers:
        - name: gatling-report-collater
          image: ${IMAGE}
          volumeMounts:
          - mountPath: /opt/gatling/${GATLING_REPORT_DIR}
            name: loadtest
        restartPolicy: Never
        volumes:
          - name: loadtest
            persistentVolumeClaim:
              claimName: loadtestclaim
parameters:
- description: The docker image of the Gatling load tester
  displayName: Image
  name: IMAGE
  required: true
- description: the parent directory for gatling report results
  displayName: Gatling Report directory
  name: GATLING_REPORT_DIR
  required: true
