apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: openshift-load-tester-job
message: |-
  A complete Load Testing mechanism using Gatling
metadata:
  annotations:
    description: |-
      Launches a number of configured Gatling load test pods to exercise a target URL
    openshift.io/display-name: Pipeline Build Example
    tags: instant-app,jenkins
  name: openshift-load-tester-job
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: gatling-load-test-job
  spec:
    parallelism: 3
    completions: 3
    template:
      metadata:
        name: gatling-load-test-job
      spec:
        containers:
        - name: gatling-load-tester
          image: ${IMAGE}
          env:
            - name: GATLING_LOG_DIR
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: GATLING_REPORT_DIR
              value: ${GATLING_REPORT_DIR}
          volumeMounts:
          - mountPath: /opt/gatling
            name: loadtest
        restartPolicy: Never
        volumes:
          - name: loadtest
            persistentVolumeClaim:
              claimName: loadtestclaim
parameters:
- description: The docker image of the Gatling load tester
  displayName: Image
  name: IMAGE
  required: true
- description: the parent directory for gatling report results
  displayName: Gatling Report directory
  name: GATLING_REPORT_DIR
  required: true
