pipeline {
  agent {
    node {
      label 'maven'

    }
  }
  options {
    timeout(time: 20, unit: 'MINUTES')
  }
  System.setProperty("hudson.model.DirectoryBrowserSupport.CSP","")
  stages {
    stage('preamble') {
        steps {
            script {
                openshift.withCluster() {
                    openshift.withProject() {
                        echo "Using project: ${openshift.project()}"
                    }
                }
            }
        }
    }

    stage ('load-test'){
      steps {
        dir("single-pod-strategy"){
          sh 'mvn -B gatling:test'
          script{
          def reportDir = sh (
            script: 'find target/gatling  -maxdepth 1 -mindepth 1 -type d',
            returnStdout: true
          ).trim()
          echo pwd()
          sh 'pwd; ls'
          archiveArtifacts artifacts: "${reportDir}/", fingerprint: true
          publishHTML (target: [
            allowMissing: false,
            alwaysLinkToLastBuild: false,
            keepAll: true,
            reportDir: "${reportDir}",
            reportFiles: 'index.html',
            reportName: "RCov Report"
         ])
         }
        }

      }
    }
  }

//  post {
//    always {
//      archiveArtifacts artifacts: 'single-pod-strategy/target/gatling/', fingerprint: true
//    }
//  }
}
