pipeline {
  agent {
    node {
      label 'maven'
    }
  }
  options {
    timeout(time: 20, unit: 'MINUTES')
  }
  stages {
    stage('preamble') {
        steps {
            script {
                openshift.withCluster() {
                    openshift.withProject() {
                        echo "Using project: ${openshift.project()}"
                    }
                }
            }
        }
    }

    stage ('load-test'){
      steps {
        dir("single-pod-strategy"){
          sh 'mvn gatling:test'
          HTML_REPORT_DIR = sh (
            script: 'find target/gatling  -maxdepth 1 -mindepth 1 -type d',
            returnStdout: true
          ).trim()
          archiveArtifacts artifacts: "${HTML_REPORT_DIR}", fingerprint: true
          publishHTML (target: [
            allowMissing: false,
            alwaysLinkToLastBuild: false,
            keepAll: true,
            reportDir: '${HTML_REPORT_DIR}',
            reportFiles: 'index.html',
            reportName: "RCov Report"
         ])
        }

      }
    }
  }

//  post {
//    always {
//      archiveArtifacts artifacts: 'single-pod-strategy/target/gatling/', fingerprint: true
//    }
//  }
}
